const data = {
  products: [
    {
      name: 'Nike Sportswear',
      category: 'Shirt',
      image: '/images/sportswear.jpg',
      price: '€32.99',
      brand: 'Nike',
      rating: '4.5',
      numRevies: '10',
      countInStock: '20',
      description:
        'Made from mid-weight cotton and featuring a loose fit, this tee has a roomy, extra-comfortable feel. The printed graphic features a patchwork design that matches up with the Air Max Airloom Footwear Collection.',
    },
    {
      name: 'Iridescent Shattered Trefoil',
      category: 'Shirt',
      image: '/images/adidasshirt.jpg',
      price: '€40.99',
      brand: 'Adidas',
      rating: '4.5',
      numRevies: '10',
      countInStock: '20',
      description: 'Women`s T-Shirt Iridescent Shattered Trefoil In White',
    },
    {
      name: 'adidas Pocket Tights',
      category: 'Pants',
      image: '/images/adidaspants.jpg',
      price: '€100.99',
      brand: 'Nike',
      rating: '4.5',
      numRevies: '10',
      countInStock: '20',
      description: 'adidas 3-Stripes 7/8 Pocket Tights Women`s',
    },
    {
      name: 'Nike Free Metcon 4',
      category: 'Shoes',
      image: '/images/trainingshoes.jpg',
      price: '€119.99',
      brand: 'Nike',
      rating: '4.5',
      numRevies: '10',
      countInStock: '20',
      description:
        'The Nike Free Metcon 4 combines flexibility with stability to help you get the most out of your training programme. Updated "chain-link" mesh cools and flexes as you speed through agility drills, while support at the midfoot and heel braces you for your heaviest sets in the weight room.',
    },
    {
      name: 'sneaker Multix',
      category: 'Shoes',
      image: '/images/adidassneaker.jpg',
      price: '€91.99',
      brand: 'Adidas',
      rating: '4.5',
      numRevies: '10',
      countInStock: '20',
      description: 'Men`s sneaker Multix in black',
    },
    {
      name: 'Fleece Metallic',
      category: 'Pants',
      image: '/images/nikepants.jpg',
      price: '€149.99',
      brand: 'Nike',
      rating: '4.5',
      numRevies: '10',
      countInStock: '20',
      description: 'Nike Air Womens Fleece Metallic Pants',
    },
  ],
};
export default data
